apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: translate-claim0
  name: translate-claim0
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: "{{ .Values.storageClassName }}"
  resources:
    requests:
      storage: 100Mi